### ISSUE TITLE
VR CPU will be reduced again, when doing 1st host reconnection

### ISSUE THREAD

**Issue by youyk** [zstackorg/zstack#65]
In system, there is only 1 zone, 1 cluster, 1 host and 1 VM, which is VR VM.

When VR is created, QueryCPU and Memory:
{
    "availableCpu": 14460,
    "availableMemory": 7181045760,
    "success": true,
    "totalCpu": 15996,
    "totalMemory": 8254787584
}

After doing ReconnectHost, QueryCPU and Memory will show:
{
    "availableCpu": 13436,
    "availableMemory": 7181045760,
    "success": true,
    "totalCpu": 15996,
    "totalMemory": 8254787584
}

The AvailableCpu will be reduced 1024, which is just VR's cpu number.

After we '''stop''' the VR VM and query CPU again, we got:
{
    "availableCpu": 14460,
    "availableMemory": 7717916672,
    "success": true,
    "totalCpu": 15996,
    "totalMemory": 8254787584
}

The issue is not stably reproduced. Still investigation why.

**Comment by youyk** [comment]
If create a brand new (clean) ZStack env from scratch, the 1st time create VM with VR VM will stably reproduce this bug. The VR CPU won't be counted.

**Comment by youyk** [comment]
Maybe this bug is not VR VM is not count down the CPU, but the Reconnect will do another round count down for VR VM.

**Comment by youyk** [comment]
Confirmed. The 1st ReconnectHost will do another round CPU reduce for VR VM.

**Comment by youyk** [comment]
1. When ZStack is deploy, hosted is added and no VM:
{
    "availableCpu": 15484,
    "availableMemory": 7717916672,
    "success": true,
    "totalCpu": 15996,
    "totalMemory": 8254787584
}

2. After create 1 VM (512Hz) with VR VM (1024Hz):
{
    "availableCpu": 13948,
    "availableMemory": 7046828032,
    "success": true,
    "totalCpu": 15996,
    "totalMemory": 8254787584
}

3. ReconnectHost
{
    "availableCpu": 12924,
    "availableMemory": 7046828032,
    "success": true,
    "totalCpu": 15996,
    "totalMemory": 8254787584
}

Redo step3 will not continue reduce VR VM's memory. When destroy all VM, the all available CPU won't come back to: 15484

**Comment by zxwing** [comment]
fixed in upstream. Please note the host is reserved 512HZ CPU for system use. so the available capacity is always 512HZ smaller than the real.

**Comment by youyk** [comment]
This bug is still existed in latest upstream. So reopen it.

Copy from test log. The res1 is before host reconnection. The res2 is after host reconnection.  You can find the value is same with previous comments. 
----------
 available CPU are different. res1: 13948, res2: 12924
----------

**Comment by zxwing** [comment]
fixed in upstream
